# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/aichat.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/aichat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/aichat.proto\x12\x06\x61ichat\"1\n\x0fGenerateRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\"$\n\x10GenerateResponse\x12\x10\n\x08response\x18\x01 \x01(\t2K\n\x06\x41iChat\x12\x41\n\x08generate\x12\x17.aichat.GenerateRequest\x1a\x18.aichat.GenerateResponse\"\x00\x30\x01\x42!\xca\x02\x0bGRPC\\AiChat\xe2\x02\x10GRPC\\GPBMetadatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.aichat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\312\002\013GRPC\\AiChat\342\002\020GRPC\\GPBMetadata'
  _globals['_GENERATEREQUEST']._serialized_start=30
  _globals['_GENERATEREQUEST']._serialized_end=79
  _globals['_GENERATERESPONSE']._serialized_start=81
  _globals['_GENERATERESPONSE']._serialized_end=117
  _globals['_AICHAT']._serialized_start=119
  _globals['_AICHAT']._serialized_end=194
# @@protoc_insertion_point(module_scope)
