version: "3"

rpc:
  listen: "tcp://127.0.0.1:6001"

http:
  address: 0.0.0.0:8888
  middleware: [ "static" ] # <-- Add static to the list of the middleware
  static:
    dir: "./public/build"
    forbid: [ "" ]
    calculate_etag: false
    weak: false
    allow: []
    request:
      input: "custom-header"
    response:
      output: "output-header"

server:
  command: "php worker.php"

  relay: "pipes"
  relay_timeout: "20s"
  env:
      APP_RUNTIME: Runtime\RoadRunnerSymfonyNyholm\Runtime

kv:
  memory-cache:
    driver: memory
    config: { }

grpc:
  listen: "tcp://127.0.0.1:9999"
  proto: ["proto/pinger.proto"]
  max_send_msg_size: 50
  max_recv_msg_size: 50
  max_connection_idle: 0s
  max_connection_age: 0s
  max_connection_age_grace: 0s
  max_concurrent_streams: 10
  ping_time: 1s
  timeout: 200s
  pool:
    num_workers: 5
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s
